CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`codigo` varchar(10),
	`dig` varchar(10),
	`ccm` varchar(20),
	`cnpj` varchar(20),
	`nome` varchar(255) NOT NULL,
	`endereco` text,
	`cidade` varchar(100),
	`estado` varchar(2),
	`cep` varchar(15),
	`inscricaoEstadual` varchar(20),
	`versao` varchar(20),
	`numeroTerminais` int,
	`usaDigHistorico` boolean DEFAULT false,
	`usaDigCCustos` boolean DEFAULT false,
	`usaDigConta` boolean DEFAULT false,
	`codigoEmpresaCliente` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`)
);
