CREATE TABLE "productCommercialInfo" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "productCommercialInfo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"precoCusto" integer DEFAULT 0 NOT NULL,
	"precoVenda" integer DEFAULT 0 NOT NULL,
	"precoTabela" integer,
	"margemLucro" integer DEFAULT 0,
	"descontoMaximo" integer DEFAULT 0,
	"comissaoVenda" integer DEFAULT 0,
	"comissaoCompra" integer DEFAULT 0,
	"markup" integer DEFAULT 0,
	"priceHistory" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "productCommercialInfo_productId_unique" UNIQUE("productId")
);
--> statement-breakpoint
CREATE TABLE "productStockInfo" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "productStockInfo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"estoqueMinimo" integer DEFAULT 0,
	"estoqueMaximo" integer,
	"pontoPedido" integer,
	"controlaLote" integer DEFAULT 1 NOT NULL,
	"controlaValidade" integer DEFAULT 1 NOT NULL,
	"prazoValidadePadrao" integer,
	"localizacaoPadrao" varchar(100),
	"tipoProduto" varchar(20) DEFAULT 'acabado' NOT NULL,
	"tempoProdução" integer,
	"rendimento" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "productStockInfo_productId_unique" UNIQUE("productId")
);
--> statement-breakpoint
CREATE TABLE "productSuppliers" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "productSuppliers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"supplierId" integer NOT NULL,
	"codigoFornecedor" varchar(50),
	"precoCusto" integer,
	"prazoEntrega" integer,
	"loteMinimoCompra" integer,
	"isPrincipal" integer DEFAULT 0,
	"prioridade" integer DEFAULT 1,
	"active" integer DEFAULT 1 NOT NULL,
	"ultimaCompra" timestamp,
	"ultimoPreco" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "productSuppliers_productId_supplierId_unique" UNIQUE("productId","supplierId")
);
--> statement-breakpoint
CREATE TABLE "productTaxInfo" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "productTaxInfo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"ncm" varchar(8) NOT NULL,
	"cest" varchar(7),
	"origem" varchar(1) DEFAULT '0' NOT NULL,
	"cfopVendaDentroEstado" varchar(4) DEFAULT '5102',
	"cfopVendaForaEstado" varchar(4) DEFAULT '6102',
	"cfopCompra" varchar(4) DEFAULT '1102',
	"cstIcms" varchar(3),
	"aliquotaIcms" integer DEFAULT 0,
	"baseCalculoIcms" integer DEFAULT 10000,
	"icmsSt" integer DEFAULT 0,
	"mva" integer DEFAULT 0,
	"cstPis" varchar(2),
	"aliquotaPis" integer DEFAULT 165,
	"baseCalculoPis" integer DEFAULT 10000,
	"cstCofins" varchar(2),
	"aliquotaCofins" integer DEFAULT 760,
	"baseCalculoCofins" integer DEFAULT 10000,
	"cstIpi" varchar(2),
	"aliquotaIpi" integer DEFAULT 0,
	"codigoEnquadramentoIpi" varchar(3),
	"aliquotaFcp" integer DEFAULT 0,
	"notes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "productTaxInfo_productId_unique" UNIQUE("productId")
);
--> statement-breakpoint
CREATE TABLE "suppliers" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "suppliers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"tradeName" varchar(255),
	"cnpj" varchar(14),
	"cpf" varchar(11),
	"ie" varchar(20),
	"im" varchar(20),
	"contactName" varchar(255),
	"phone" varchar(20),
	"email" varchar(320),
	"website" varchar(500),
	"address" text,
	"city" varchar(100),
	"state" varchar(2),
	"zipCode" varchar(8),
	"country" varchar(2) DEFAULT 'BR',
	"paymentTerms" varchar(255),
	"deliveryTime" integer,
	"minOrderValue" integer,
	"rating" integer,
	"isCertified" integer DEFAULT 0,
	"certifications" text,
	"active" integer DEFAULT 1 NOT NULL,
	"notes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "suppliers_cnpj_unique" UNIQUE("cnpj"),
	CONSTRAINT "suppliers_cpf_unique" UNIQUE("cpf")
);
